name_mapping = [
   { "convert": [(11, "Abdel Wadoud Abdalla Abdellatif"), (14, "Abdelwadoud Abdalla Abdel Latif"), ], "to": "Abdel Wadoud Abdalla Abdellatif" },
   { "convert": [(15, "Abdul-Mawla Khalid Antanious"), (16, "Abdul-Mawla Khalid Antinous"), (25, "Abid-Almawla Khalid Antanious"), ], "to": "Abdul-Mawla Khalid Antanious" },
   { "convert": [(27, "Abizcorreta Guillerm[o]"), (294, "Arizcorreta Guillermo"), ], "to": "Arizcorreta Guillermo" },
   { "convert": [(29, "Ablakwa E T"), (30, "Ablakwa E. T."), ], "to": "Ablakwa E T" },
   { "convert": [(35, "Abrahamian Sarkis"), (36, "Abrahamian Sarkis Sarkis"), ], "to": "Abrahamian Sarkis" },
   { "convert": [(41, "Abu-Middain Hussein F."), (42, "Abu-Middain Hussein Freih"), ], "to": "Abu-Middain Hussein F." },
   { "convert": [(46, "Abubaker Ahdmed Ali"), (47, "Abubaker Ahmed Ali"), (48, "Abubakr Ahmed S."), ], "to": "Abubaker Ahdmed Ali" },
   { "convert": [(68, "Adigwe Christopher A"), (70, "Adigwf Christopher A"), ], "to": "Adigwe Christopher A" },
   { "convert": [(69, "Adigwe Mary Akun"), (71, "Adigwfe Mary Akon"), ], "to": "Adigwe Mary Akun" },
   { "convert": [(89, "Aghaloo Amir M"), (90, "Aghaloo Amir Mohsen"), ], "to": "Aghaloo Amir M" },
   { "convert": [(101, "Aguirre Reinaldo "), (264, "Aquirre Reinaldo M"), ], "to": "Aguirre Reinaldo " },
   { "convert": [(106, "Ahmad Ifran I"), (107, "Ahmad Irfan I"), ], "to": "Ahmad Ifran I" },
   { "convert": [(110, "Ahmad Syed Naeem"), (111, "Ahmad Syed Nasim"), ], "to": "Ahmad Syed Naeem" },
   { "convert": [(114, "Ahmed  Othman A"), (121, "Ahmed Othman A"), ], "to": "Ahmed Othman A" },
   { "convert": [(119, "Ahmed Othman"), (121, "Ahmed Othman A"), ], "to": "Ahmed Othman A" },
   { "convert": [(134, "Akerlund Stem O"), (136, "Akerlund Sten O"), ], "to": "Akerlund Sten O" },
   { "convert": [(140, "Akintola Peter A"), (141, "Akintola Peter Alabi"), ], "to": "Akintola Peter A" },
   { "convert": [(149, "Al-Azzawy Abdul-Jabbar Saleh"), (150, "Al-Azzawy Abduljabbar Saleh"), ], "to": "Al-Azzawy Abdul-Jabbar Saleh" },
   { "convert": [(152, "Al-Khudairy Farid (Fred) Khalid"), (153, "Al-Khudairy Fred Khalid"), (1605, "Il Khudairy Farid Khalid"), ], "to": "Al-Khudairy Farid (Fred) Khalid" },
   { "convert": [(168, "Alavi Siraj M"), (169, "Alavi Siraj M."), ], "to": "Alavi Siraj M" },
   { "convert": [(172, "Albar[b]ian Gabriel A"), (173, "Albarian Gabriel A"), ], "to": "Albarian Gabriel A" },
   { "convert": [(180, "Alfonso Pedro E"), (181, "Alfonso Pedro Jose"), ], "to": "Alfonso Pedro E" },
   { "convert": [(190, "Ali Mohamed"), (1212, "Galil Mohamed"), ], "to": "Ali Mohamed" },
   { "convert": [(195, "Alikian Arsen N"), (196, "Alikian Arsen N."), ], "to": "Alikian Arsen N" },
   { "convert": [(197, "Aliussaui Ali M J"), (202, "Almussawi Ali M J"), ], "to": "Aliussaui Ali M J" },
   { "convert": [(237, "Andronicou Andreas"), (238, "Andronicou Andreas "), ], "to": "Andronicou Andreas" },
   { "convert": [(255, "Anyim Okechukwu A"), (256, "Anyim Okechukwu A."), ], "to": "Anyim Okechukwu A" },
   { "convert": [(262, "Aqqad Mohammad A.R."), (263, "Aqqad Muhammad A.R."), ], "to": "Aqqad Mohammad A.R." },
   { "convert": [(266, "Arabi Hassan"), (275, "Arbabi Hassan"), ], "to": "Arabi Hassan" },
   { "convert": [(272, "Araujo Schneider Coalho de"), (274, "Araujo Schneider Coelho de"), (273, "Araujo Schneider Coelho"), ], "to": "Araujo Schneider Coalho de" },
   { "convert": [(283, "Argoud Mauricio H."), (284, "Argoud Mauricio Hourani"), ], "to": "Argoud Mauricio H." },
   { "convert": [(288, "Arguello Fabio"), (289, "Arguello Fabio V."), ], "to": "Arguello Fabio" },
   { "convert": [(295, "Armerding George K"), (296, "Armering George K."), ], "to": "Armerding George K" },
   { "convert": [(301, "Arslan Ohmet"), (328, "Aslan Ahmet"), ], "to": "Arslan Ohmet" },
   { "convert": [(309, "Ascarrunz Francisco Javier"), (317, "Asearruns Francisco Javier"), ], "to": "Ascarrunz Francisco Javier" },
   { "convert": [(321, "Ashna Mahammed"), (322, "Ashna Mohammad"), ], "to": "Ashna Mahammed" },
   { "convert": [(341, "Aulakh Gulzar"), (342, "Aulakh Gulzar S"), ], "to": "Aulakh Gulzar S" },
   { "convert": [(358, "Aylsworth William W"), (359, "Aylsworth William W."), ], "to": "Aylsworth William W" },
   { "convert": [(360, "Ayubi Parvia"), (361, "Ayubi Parvis"), ], "to": "Ayubi Parvia" },
   { "convert": [(364, "Azari Jamshid"), (365, "Azari Janshid"), ], "to": "Azari Jamshid" },
   { "convert": [(368, "Azzi Yusuf A.M."), (370, "Azzi Yusuf Abel M."), ], "to": "Azzi Yusuf A.M." },
   { "convert": [(371, "Baagie Francis"), (378, "Badgie Francis"), ], "to": "Baagie Francis" },
   { "convert": [(374, "Babikian Zaven G."), (375, "Babikian Zaven Garabid"), ], "to": "Babikian Zaven G." },
   { "convert": [(381, "Badii Lo fali"), (382, "Badii Lotfali"), ], "to": "Badii Lo fali" },
   { "convert": [(389, "Bahatia Tirlochan S"), (495, "Bhatia Tirlochan S"), (488, "Bhastia Tirlochan S."), ], "to": "Bahatia Tirlochan S" },
   { "convert": [(391, "Bain Majnit Kumar"), (392, "Bain Manjit Jumar"), ], "to": "Bain Majnit Kumar" },
   { "convert": [(405, "Baluch Mohammed A"), (406, "Baluch Muhammad A"), ], "to": "Baluch Mohammed A" },
   { "convert": [(411, "Barelli Emanuel"), (412, "Barelli Emanuele"), ], "to": "Barelli Emanuel" },
   { "convert": [(413, "Barjestah Z M"), (414, "Barjesteh Z M"), (415, "Barjesteh Z. M. "), ], "to": "Barjesteh Z M" },
   { "convert": [(419, "Barpal Itzchak R"), (420, "Barpal Itzchak R."), ], "to": "Barpal Itzchak R" },
   { "convert": [(422, "Barrenechea Alberto Manuel"), (423, "Barreneches Albert M."), ], "to": "Barrenechea Alberto Manuel" },
   { "convert": [(429, "Barzegar Nour"), (557, "Brarzegar Nour"), ], "to": "Barzegar Nour" },
   { "convert": [(433, "Bateman William V"), (434, "Bateman Wlliam V"), ], "to": "Bateman William V" },
   { "convert": [(436, "Batmanghelidj A"), (543, "BotmanghelIdj A."), ], "to": "Batmanghelidj A" },
   { "convert": [(450, "Bedri Ahmed Abdelkarim"), (451, "Bedri Mohammed Abdelkarim"), ], "to": "Bedri Mohammed Abdelkarim" },
   { "convert": [(452, "Beer Amnon"), (453, "Beer Amon"), ], "to": "Beer Amnon" },
   { "convert": [(457, "Behnam Amir A"), (458, "Behnam Amir Ahmad"), ], "to": "Behnam Amir A" },
   { "convert": [(462, "Beklik Mohammad"), (463, "Beklik Mohemad"), ], "to": "Beklik Mohammad" },
   { "convert": [(465, "Beleil Osman M"), (466, "Beleil Osman Mohed"), ], "to": "Beleil Osman M" },
   { "convert": [(468, "Belvi Gurcharan Singh"), (481, "Bevli Gurcharan Singh"), (975, "Deol Gurcharn Singh"), ], "to": "Belvi Gurcharan Singh" },
   { "convert": [(478, "Berutti Paulo Azevdo"), (479, "Berutti Paulo Azevedo"), ], "to": "Berutti Paulo Azevdo" },
   { "convert": [(484, "Bhangoo Darshan S"), (486, "Bhasin Darshan S"), ], "to": "Bhangoo Darshan S" },
   { "convert": [(487, "Bhastia Harinder S."), (492, "Bhatia Harinder S"), ], "to": "Bhatia Harinder S" },
   { "convert": [(489, "Bhastin Darshan S. "), (486, "Bhasin Darshan S"), ], "to": "Bhastin Darshan S. " },
   { "convert": [(491, "Bhatia Apar Singh"), (1265, "Ghatia Apar Singh"), ], "to": "Bhatia Apar Singh" },
   { "convert": [(494, "Bhatia Surinder K "), (492, "Bhatia Harinder S"), ], "to": "Bhatia Harinder S" },
   { "convert": [(499, "Bhojak Trilok Chandra"), (500, "Bhojak Trilokchandra"), ], "to": "Bhojak Trilok Chandra" },
   { "convert": [(505, "Bienert Doug H"), (506, "Bienert Doug H."), (507, "Bienert Douglas H"), ], "to": "Bienert Doug H" },
   { "convert": [(518, "Boghosian Hagop Kaspar"), (519, "Boghosian Hagop Kasper"), ], "to": "Boghosian Hagop Kaspar" },
   { "convert": [(570, "Bryant Robert Percy"), (571, "Bryant Robert Percy "), ], "to": "Bryant Robert Percy" },
   { "convert": [(581, "Bungai Welsing"), (582, "Bungia Welsing"), ], "to": "Bungai Welsing" },
   { "convert": [(586, "Burmeister Karin E"), (587, "Burmeister Karin E."), ], "to": "Burmeister Karin E" },
   { "convert": [(589, "Bustamante Juan"), (590, "Bustamente Juan"), ], "to": "Bustamante Juan" },
   { "convert": [(606, "Calderon George J"), (607, "Calderon George R."), ], "to": "Calderon George R." },
   { "convert": [(608, "Calderon Juan M."), (609, "Calderon Juan M. "), (610, "Calderon Juan Manuel"), ], "to": "Calderon Juan M." },
   { "convert": [(630, "Carranzana German"), (632, "Carrazana German P."), ], "to": "Carranzana German" },
   { "convert": [(641, "Carvalho Antinous Souza"), (642, "Carvalho Antonous S. "), ], "to": "Carvalho Antinous Souza" },
   { "convert": [(643, "Carvalho Ian Sousa"), (644, "Carvalho Ib Souza"), ], "to": "Carvalho Ian Sousa" },
   { "convert": [(656, "Cawi Horst G"), (657, "Cawi Horst G."), ], "to": "Cawi Horst G" },
   { "convert": [(666, "Chacko Joe"), (669, "Chacko Joseph"), (667, "Chacko John"), ], "to": "Chacko Joseph" },
   { "convert": [(668, "Chacko John "), (667, "Chacko John"), (666, "Chacko Joe"), ], "to": "Chacko John " },
   { "convert": [(672, "Chad Reuben"), (2690, "Ohad Reuben"), ], "to": "Chad Reuben" },
   { "convert": [(688, "Chan Chiucheung"), (698, "Chan Shiucheung"), ], "to": "Chan Shiucheung" },
   { "convert": [(699, "Chan Shiuchfung"), (698, "Chan Shiucheung"), ], "to": "Chan Shiucheung" },
   { "convert": [(700, "Chan Warner H"), (720, "Chang Warner H."), ], "to": "Chang Warner H." },
   { "convert": [(702, "Chandler Trevor L"), (703, "Chandler Trevor L."), ], "to": "Chandler Trevor L" },
   { "convert": [(705, "Chandra Pravosh"), (742, "Chaundra Pravosh"), ], "to": "Chandra Pravosh" },
   { "convert": [(734, "Chau Phan Ngoc"), (1479, "Hau Phan Ngoc"), ], "to": "Chau Phan Ngoc" },
   { "convert": [(740, "Chauhan Baldev R"), (741, "Chauhan Baldev R."), ], "to": "Chauhan Baldev R" },
   { "convert": [(743, "Chavdarian Peniamin"), (3587, "Tchavdarian Peniamin "), ], "to": "Chavdarian Peniamin" },
   { "convert": [(745, "Chazal Samip"), (1267, "Ghazal Samir"), ], "to": "Chazal Samip" },
   { "convert": [(750, "Chen Houston D"), (751, "Chen Houston D."), ], "to": "Chen Houston D" },
   { "convert": [(771, "Chihaya  Masaharu "), (773, "Chihaya Masaharu"), ], "to": "Chihaya Masaharu" },
   { "convert": [(774, "Chikahaoui Ahmed"), (775, "Chikhaoui Ahmed"), ], "to": "Chikahaoui Ahmed" },
   { "convert": [(776, "Chilingerian Avedis"), (777, "Chillingerian Avedis"), ], "to": "Chilingerian Avedis" },
   { "convert": [(782, "Chiu John Yuen Po"), (784, "Chiu Yuen Po"), ], "to": "Chiu Yuen Po" },
   { "convert": [(794, "Chou Jai Hyun"), (3096, "Ryu Jai Hyun"), ], "to": "Chou Jai Hyun" },
   { "convert": [(800, "Chow Andre Y"), (886, "Cow Andre Y"), ], "to": "Chow Andre Y" },
   { "convert": [(801, "Chow Joseph H S"), (802, "Chow Joseph J. S."), ], "to": "Chow Joseph H S" },
   { "convert": [(808, "Christie Hal Hans"), (809, "Christie Harold H"), ], "to": "Christie Hal Hans" },
   { "convert": [(810, "Christodoulopoulos D"), (812, "Christodoulopoulos D "), ], "to": "Christodoulopoulos D" },
   { "convert": [(815, "Chu Benny Kokwai"), (816, "Chu Benny Kwokmai"), ], "to": "Chu Benny Kokwai" },
   { "convert": [(822, "Chu Victor"), (823, "Chu Victor "), ], "to": "Chu Victor" },
   { "convert": [(828, "Chukwu Ambrose N C"), (829, "Chukwu Ambrose N. C."), ], "to": "Chukwu Ambrose N C" },
   { "convert": [(830, "Chukwu Chairty C."), (831, "Chukwu Charity C"), ], "to": "Chukwu Chairty C." },
   { "convert": [(838, "Chung Jong Rak"), (839, "Chung Jong Tak"), ], "to": "Chung Jong Rak" },
   { "convert": [(847, "Cisneros Antonio J"), (848, "Cisneros Antonio J. "), ], "to": "Cisneros Antonio J" },
   { "convert": [(860, "Colom Jose M"), (861, "Colom Jose Manuel"), ], "to": "Colom Jose M" },
   { "convert": [(864, "Constantinides Anastasios"), (865, "Constantinides Anastasios "), ], "to": "Constantinides Anastasios" },
   { "convert": [(867, "Cooper Gary W"), (868, "Cooper Gary W."), ], "to": "Cooper Gary W" },
   { "convert": [(879, "Cortes Roberto H"), (880, "Cortes Roberto H."), ], "to": "Cortes Roberto H" },
   { "convert": [(882, "Costa Vasco F Jr"), (883, "Costa Vasco F. Jr."), ], "to": "Costa Vasco F Jr" },
   { "convert": [(890, "Cranko Oliver A.M."), (891, "Cranko Oliver Albert M."), ], "to": "Cranko Oliver A.M." },
   { "convert": [(904, "Custode Franklin Z"), (905, "Custode Frnklin Z"), ], "to": "Custode Franklin Z" },
   { "convert": [(906, "Cutti C. Jesus Faustino"), (908, "Cutti J. Faustino"), ], "to": "Cutti C. Jesus Faustino" },
   { "convert": [(910, "Dadabhoy Salim"), (911, "Dadabhoy Salim D"), (913, "Dadashoy Salim"), ], "to": "Dadabhoy Salim" },
   { "convert": [(921, "Damues Paul L"), (922, "Damues Paul L."), ], "to": "Damues Paul L" },
   { "convert": [(923, "Dan Kintafo Ali"), (927, "Dankintafo Ali"), ], "to": "Dan Kintafo Ali" },
   { "convert": [(937, "Datta Subhash K"), (938, "Datta Subhash K."), ], "to": "Datta Subhash K" },
   { "convert": [(939, "Davalos Jr Ruben Cimarron"), (940, "Davalos Ruben Cimarron, Jr."), ], "to": "Davalos Jr Ruben Cimarron" },
   { "convert": [(941, "Davidson Menachem"), (942, "Davidson Menachem M"), ], "to": "Davidson Menachem" },
   { "convert": [(947, "De Albuguerque Klaus"), (948, "De Albuquerque Klaus"), ], "to": "De Albuguerque Klaus" },
   { "convert": [(951, "De Medeires Reinaldo Jacinto "), (952, "De Medeiros Reinaldo J"), ], "to": "De Medeires Reinaldo Jacinto " },
   { "convert": [(961, "Dehestani Abdolali"), (962, "Dehestani Abdolali "), ], "to": "Dehestani Abdolali" },
   { "convert": [(965, "Deleon Garth D"), (966, "Deleon Garth D."), ], "to": "Deleon Garth D" },
   { "convert": [(980, "Derinter Leonardus"), (989, "Dewinter Leonardus"), ], "to": "Dewinter Leonardus" },
   { "convert": [(992, "Dhaliwal Mohindan Singh"), (993, "Dhaliwal Mohindar Singh"), (994, "Dhaliwal Mohinder Singh"), ], "to": "Dhaliwal Mohindan Singh" },
   { "convert": [(996, "Dhatt Gurdial"), (997, "Dhatt Gurdial Singh"), ], "to": "Dhatt Gurdial" },
   { "convert": [(1031, "Dreksler Moshe Jehuda "), (1032, "Dreksler Moshe Yehuda"), ], "to": "Dreksler Moshe Jehuda " },
   { "convert": [(1038, "Duenas Eduardo M"), (1039, "Duenas Eduardo M."), ], "to": "Duenas Eduardo M" },
   { "convert": [(1047, "Ebrahim Mohamed A"), (1595, "Ibrahim Mohammed Y"), (1594, "Ibrahim Mohammad Y"), ], "to": "Ebrahim Mohamed A" },
   { "convert": [(1054, "Economou Costas Spyras"), (1055, "Economou Costas Spyros"), ], "to": "Economou Costas Spyros" },
   { "convert": [(1059, "El Hussein Gaafar El Hassan"), (1060, "El-Hussein Gaafar El-Hassan"), ], "to": "El Hussein Gaafar El Hassan" },
   { "convert": [(1061, "El-Oubari Adel Akee"), (1062, "El-Oubari Adel Akef"), ], "to": "El-Oubari Adel Akee" },
   { "convert": [(1063, "Elajili Hedi"), (1168, "Flajili Hedi"), ], "to": "Elajili Hedi" },
   { "convert": [(1076, "Emami Manouchehr"), (1744, "Karami Manouchehr"), (3352, "Siani Manouchehr"), ], "to": "Karami Manouchehr" },
   { "convert": [(1095, "Espinosa Manuel E"), (1096, "Espinosa Manuel E."), ], "to": "Espinosa Manuel E" },
   { "convert": [(1136, "Fatani Mohamed N"), (1137, "Fatani Mohamed Noor"), ], "to": "Fatani Mohamed N" },
   { "convert": [(1148, "Fayyasz Sanavi M"), (1150, "Fayyaz Sanavi M"), ], "to": "Fayyasz Sanavi M" },
   { "convert": [(1174, "Fock Poon Yuen"), (1178, "Fook Poon Yuen"), (1179, "Fook Poun Yuen"), ], "to": "Fock Poon Yuen" },
   { "convert": [(1195, "Fuenmayor Romer H"), (1196, "Fuenmayor Romer H."), ], "to": "Fuenmayor Romer H" },
   { "convert": [(1211, "Galiando Miguel Angel"), (1215, "Galindo Miguel Angel"), ], "to": "Galiando Miguel Angel" },
   { "convert": [(1217, "Gamini Mohammad Ali"), (3210, "Sartipi Mohammad Ali"), ], "to": "Gamini Mohammad Ali" },
   { "convert": [(1221, "Gaoiran Fortunato S"), (1222, "Gaoiran Fortunato S."), (1223, "Gaoiran Fortunato Simeon"), ], "to": "Gaoiran Fortunato S" },
   { "convert": [(1236, "Garza Alfonso Jose"), (1237, "Garza Alfonso Jr."), ], "to": "Garza Alfonso Jose" },
   { "convert": [(1241, "Gbadebo Joseph"), (1342, "Gradebo Jospeh"), ], "to": "Gbadebo Joseph" },
   { "convert": [(1244, "Georgopoulos Elias J."), (1245, "Georgopoulos Elias John"), ], "to": "Georgopoulos Elias J." },
   { "convert": [(1253, "Ghalayini Mahmoud S."), (1254, "Ghalayini Mahmoud Saadedine"), ], "to": "Ghalayini Mahmoud S." },
   { "convert": [(1256, "Ghalib Iyad A. "), (1257, "Ghalib Iyad Ali"), ], "to": "Ghalib Iyad A. " },
   { "convert": [(1278, "Ghulam Basim Y."), (1279, "Ghulam Basim Yousef"), ], "to": "Ghulam Basim Y." },
   { "convert": [(1288, "Gill Mohan S"), (1289, "Gill Mohan Singh"), ], "to": "Gill Mohan S" },
   { "convert": [(1290, "Gill Mohinder Singh"), (1289, "Gill Mohan Singh"), (994, "Dhaliwal Mohinder Singh"), ], "to": "Gill Mohinder Singh" },
   { "convert": [(1292, "Girbal Fecerico E."), (1293, "Girbal Federico E."), ], "to": "Girbal Fecerico E." },
   { "convert": [(1300, "Gohodsian Manoochehr"), (3457, "Soroushian Manoochehr"), ], "to": "Gohodsian Manoochehr" },
   { "convert": [(1304, "Gomes Jose Da Rocha"), (1308, "Gomez Jose Da Rocha"), ], "to": "Gomes Jose Da Rocha" },
   { "convert": [(1319, "Gonzales Hugo"), (1325, "Gonzalez Hugo"), ], "to": "Gonzales Hugo" },
   { "convert": [(1321, "Gonzales Victor A"), (1330, "Gonzalez Victor A."), ], "to": "Gonzales Victor A" },
   { "convert": [(1327, "Gonzalez Ricardo M"), (1328, "Gonzalez Ricardo M."), ], "to": "Gonzalez Ricardo M" },
   { "convert": [(1344, "Grant F Byron"), (1345, "Grant Floyd Byron"), ], "to": "Grant F Byron" },
   { "convert": [(1351, "Grewal Jasmohinder S."), (1355, "Grewal Pavinder S. "), ], "to": "Grewal Jasmohinder S." },
   { "convert": [(1354, "Grewal Pavinder S"), (1355, "Grewal Pavinder S. "), ], "to": "Grewal Pavinder S" },
   { "convert": [(1365, "Gueramian Nosrat A."), (1366, "Gueramian Nosrat Allah"), ], "to": "Gueramian Nosrat A." },
   { "convert": [(1381, "Gumucio Rene V. "), (1392, "Gurrucio Rene V."), ], "to": "Gumucio Rene V. " },
   { "convert": [(1407, "Hadizadeh Raissi M"), (1408, "Hadizadeh Raissi M."), ], "to": "Hadizadeh Raissi M" },
   { "convert": [(1420, "Haj-Shah-Mohamadlou Hooshang"), (1424, "Hajshahmohamadlou Hooshang"), (1423, "Hajshahmohamadlou Hooshan"), ], "to": "Haj-Shah-Mohamadlou Hooshang" },
   { "convert": [(1425, "Hakim Albert"), (1428, "Hakimian Albert"), ], "to": "Hakimian Albert" },
   { "convert": [(1426, "Hakimi Manoucher"), (1427, "Hakimi Manoucher "), (1076, "Emami Manouchehr"), ], "to": "Hakimi Manoucher" },
   { "convert": [(1430, "Hakkak Fahmi A M"), (1431, "Hakkak Fahmi A.M."), ], "to": "Hakkak Fahmi A M" },
   { "convert": [(1432, "Halaby Suhail S"), (1433, "Halaby Suhail S."), ], "to": "Halaby Suhail S" },
   { "convert": [(1436, "Hall Ian Elliot"), (1437, "Hall Ian Elliott"), ], "to": "Hall Ian Elliot" },
   { "convert": [(1445, "Hamidi Hossein"), (2159, "Maadi Hossein"), ], "to": "Hamidi Hossein" },
   { "convert": [(1450, "Hammond Leslie"), (1451, "Hammond Leslie John"), ], "to": "Hammond Leslie" },
   { "convert": [(1478, "Hatheway Michael E"), (1517, "Hetheway Michael E"), ], "to": "Hatheway Michael E" },
   { "convert": [(1492, "Henley Orlando"), (1493, "Henley Orlando Jose"), ], "to": "Henley Orlando" },
   { "convert": [(1497, "Heres Mohamed"), (1503, "Hermes Mohamed"), ], "to": "Heres Mohamed" },
   { "convert": [(1498, "Hereso Felisicimo R"), (1500, "Hereso Felisicimo Rafael"), ], "to": "Hereso Felisicimo R" },
   { "convert": [(1511, "Hernandez Stevens A"), (1512, "Hernandez Stevens A."), ], "to": "Hernandez Stevens A" },
   { "convert": [(1521, "Hildebrandt Werner"), (1520, "Hildebrandt Lore"), ], "to": "Hildebrandt Werner" },
   { "convert": [(1528, "Hoang Dham"), (1530, "Hoang Pham"), ], "to": "Hoang Dham" },
   { "convert": [(1532, "Hoferos Demetrio Lanuza"), (3056, "Roferos Demetrio Lanuza "), ], "to": "Hoferos Demetrio Lanuza" },
   { "convert": [(1535, "Holsheu Dietrich"), (1537, "Holzheu Dietrich"), ], "to": "Holzheu Dietrich" },
   { "convert": [(1545, "Hora Harminder Singh"), (3411, "Sodhi Harinder Singh"), ], "to": "Hora Harminder Singh" },
   { "convert": [(1552, "Hott Jorge"), (1553, "Hott Jorge A"), ], "to": "Hott Jorge" },
   { "convert": [(1556, "Hsu Chih-Kien"), (1557, "Hsu Chin Kien"), ], "to": "Hsu Chih-Kien" },
   { "convert": [(1561, "Hsueh Teddy Ta-Tse"), (1562, "Hsueh Teddy Ta-Tze"), ], "to": "Hsueh Teddy Ta-Tse" },
   { "convert": [(1565, "Hu Shung Chiao"), (1566, "Hu Sung Chiao"), ], "to": "Hu Shung Chiao" },
   { "convert": [(1577, "Hummeida Musfafa A"), (1578, "Hummeida Mustafa A"), ], "to": "Hummeida Musfafa A" },
   { "convert": [(1582, "Hung Nelson"), (1872, "King Nelson"), ], "to": "Hung Nelson" },
   { "convert": [(1599, "Idadimoghaddam Bijan"), (1632, "Izadimoghaddam Bijan"), ], "to": "Idadimoghaddam Bijan" },
   { "convert": [(1603, "Ikeda Minoru"), (1604, "Ikeda Minoru "), ], "to": "Ikeda Minoru" },
   { "convert": [(1609, "Ince Ebrem"), (1610, "Ince Ekram"), ], "to": "Ince Ebrem" },
   { "convert": [(1628, "Ito Kii Chi"), (1629, "Ito Kiichi"), ], "to": "Ito Kii Chi" },
   { "convert": [(1633, "Jaber Imad R"), (1634, "Jaber Imad Rachid"), ], "to": "Jaber Imad R" },
   { "convert": [(1637, "Jacob Freddie E"), (1638, "Jacob Teddie E"), ], "to": "Jacob Freddie E" },
   { "convert": [(1645, "Jain Nem Chand"), (1646, "Jain New Chand"), ], "to": "Jain Nem Chand" },
   { "convert": [(1648, "Jain Satish K"), (1649, "Jain Satish K."), ], "to": "Jain Satish K" },
   { "convert": [(1654, "Jama Isgail H"), (1655, "Jama Ismail H."), ], "to": "Jama Isgail H" },
   { "convert": [(1661, "Jarpa Jorge"), (1662, "Jarpa Jorge A"), ], "to": "Jarpa Jorge" },
   { "convert": [(1664, "Jarrett Manuel W"), (1665, "Jarrett Manuel W."), ], "to": "Jarrett Manuel W" },
   { "convert": [(1669, "Javedah Manoucher"), (1670, "Javedan Manoucher"), ], "to": "Javedah Manoucher" },
   { "convert": [(1685, "Jimenez Ernesto B"), (1686, "Jimenez Ernesto B."), ], "to": "Jimenez Ernesto B" },
   { "convert": [(1690, "Jirasook Panyak"), (1691, "Jirasook Panyar"), ], "to": "Jirasook Panyak" },
   { "convert": [(1698, "Joodi Khalid A"), (1699, "Joodi Khalid A."), ], "to": "Joodi Khalid A" },
   { "convert": [(1706, "Jume'an Nayif Ibrahim "), (1707, "Jumelan Nayif Ibrahim"), ], "to": "Jume'an Nayif Ibrahim " },
   { "convert": [(1717, "Kalara Chandraprakash"), (1720, "Kalra Chandraprakash"), ], "to": "Kalara Chandraprakash" },
   { "convert": [(1718, "Kalb Richard H"), (1719, "Kalib Richard H."), ], "to": "Kalb Richard H" },
   { "convert": [(1721, "Kalra Ramesh"), (1722, "Kalra Ramesh Chand"), ], "to": "Kalra Ramesh" },
   { "convert": [(1728, "Kamali Theodore"), (1729, "Kamalu Theodore"), ], "to": "Kamali Theodore" },
   { "convert": [(1752, "Kasbati Mohammed Y"), (2266, "Maskatia Mohammed Y"), ], "to": "Kasbati Mohammed Y" },
   { "convert": [(1754, "Kashanipour H"), (1755, "Kashanipour Hossein"), ], "to": "Kashanipour Hossein" },
   { "convert": [(1762, "Katagum Ibrahim N"), (1763, "Katagum Ibrahim N."), ], "to": "Katagum Ibrahim N" },
   { "convert": [(1771, "Kazemi Hamdollah"), (1773, "Kazemi-Arbat Hamdollah"), (1772, "Kazemi Saidallah"), ], "to": "Kazemi Hamdollah" },
   { "convert": [(1780, "Kelner Shalom M"), (1781, "Kelner Shalom M."), ], "to": "Kelner Shalom M" },
   { "convert": [(1785, "Kesses Evangelos G"), (1786, "Kesses Evangelos G."), ], "to": "Kesses Evangelos G" },
   { "convert": [(1795, "Khalkhali Iraj G"), (1796, "Khalkhali Iraj G."), ], "to": "Khalkhali Iraj G" },
   { "convert": [(1798, "Khamis Ibrahib G"), (1799, "Khamis Ibrahim G"), ], "to": "Khamis Ibrahib G" },
   { "convert": [(1804, "Khan Dilawer Sher"), (1805, "Khan Dilawer Sher "), ], "to": "Khan Dilawer Sher" },
   { "convert": [(1806, "Khan Mohamad Aslam"), (1807, "Khan Mohammed Aslam"), ], "to": "Khan Mohamad Aslam" },
   { "convert": [(1815, "Khan Sultan Warris"), (1816, "Khan Sultan Warris "), ], "to": "Khan Sultan Warris" },
   { "convert": [(1823, "Khatchaturian Albert A."), (1824, "Khatchaturian Albert A.B."), ], "to": "Khatchaturian Albert A." },
   { "convert": [(1826, "Khawaja Amanullah"), (1827, "Khawaja Amanullah "), ], "to": "Khawaja Amanullah" },
   { "convert": [(1835, "Khodaifar Hoosein"), (1836, "Khodaifar Hossein"), ], "to": "Khodaifar Hoosein" },
   { "convert": [(1837, "Khogali Mohamed E A"), (1838, "Khogali Mohamed E. A. "), ], "to": "Khogali Mohamed E A" },
   { "convert": [(1840, "Khorsand Mohammad"), (1841, "Khorsand Mohammad H."), ], "to": "Khorsand Mohammad" },
   { "convert": [(1842, "Khorshid Tasnim"), (1848, "Khurshid Tasnim"), ], "to": "Khorshid Tasnim" },
   { "convert": [(1851, "Kigilioglu Nadir A"), (1852, "Kigilioglu Nadir Ahmet"), ], "to": "Kigilioglu Nadir A" },
   { "convert": [(1853, "Kiiamura Yoshimiko"), (1880, "Kitamura Yushihiko"), ], "to": "Kiiamura Yoshimiko" },
   { "convert": [(1867, "Kim Young Ha"), (1868, "Kim Young Za"), ], "to": "Kim Young Ha" },
   { "convert": [(1882, "Kiziltan Fikret"), (1883, "Kiziltan Fikret "), ], "to": "Kiziltan Fikret" },
   { "convert": [(1914, "Koulaouzides A"), (1915, "Koulaouzides A."), ], "to": "Koulaouzides A" },
   { "convert": [(1937, "Kurlaender Azriel"), (1938, "Kurlaender Azriel "), ], "to": "Kurlaender Azriel" },
   { "convert": [(1943, "Kwan Joan Tai Chung"), (1944, "Kwan Joan Tai Chung "), ], "to": "Kwan Joan Tai Chung" },
   { "convert": [(1948, "Kyriakis Anthony"), (1949, "Kyriakis Anthony E"), (1950, "Kyriakis Anthony E."), ], "to": "Kyriakis Anthony" },
   { "convert": [(1951, "LaValle Carlos "), (2004, "Lavalle Carlos "), (2005, "Lavalle S Carlos "), ], "to": "LaValle Carlos " },
   { "convert": [(1963, "Lall Suresh B"), (1964, "Lall Suresh B."), ], "to": "Lall Suresh B" },
   { "convert": [(1995, "Lau Pablo A"), (2065, "Leu Pablo A."), ], "to": "Lau Pablo A" },
   { "convert": [(1997, "Lau Stepehen CK"), (1999, "Lau Stephen CK"), (1998, "Lau Stephen C.K."), ], "to": "Lau Stepehen CK" },
   { "convert": [(2009, "Laville Benoit"), (2010, "Laville Benoit "), ], "to": "Laville Benoit" },
   { "convert": [(2014, "Lazo Anuel A"), (2015, "Lazo Manuel A"), ], "to": "Lazo Anuel A" },
   { "convert": [(2016, "Lazo Manuel Augusto"), (2015, "Lazo Manuel A"), ], "to": "Lazo Manuel Augusto" },
   { "convert": [(2017, "Le Chinh Trung"), (2018, "Le Chinh Trung "), ], "to": "Le Chinh Trung" },
   { "convert": [(2019, "Le Chu Chung"), (2117, "Lo Chu Chung"), ], "to": "Le Chu Chung" },
   { "convert": [(2031, "Lee Conrad Y"), (2032, "Lee Conrad Y."), ], "to": "Lee Conrad Y" },
   { "convert": [(2048, "Lee Yoon Hui"), (2049, "Lee Yoong Lim"), ], "to": "Lee Yoon Hui" },
   { "convert": [(2055, "Lemoine David G"), (2056, "Lemoine David G."), ], "to": "Lemoine David G" },
   { "convert": [(2058, "Leon Jhon Hermes"), (2063, "Leonjhong Hermes "), ], "to": "Leon Jhon Hermes" },
   { "convert": [(2069, "Leung Teresa K"), (2070, "Leung Teresa K."), ], "to": "Leung Teresa K" },
   { "convert": [(2073, "Lev Oded"), (2074, "Lev Odede"), ], "to": "Lev Oded" },
   { "convert": [(2080, "Lewanika Beatrice I"), (2081, "Lewanika Beatrice I."), ], "to": "Lewanika Beatrice I" },
   { "convert": [(2083, "Lewanika George M I"), (2084, "Lewanika George M. I."), ], "to": "Lewanika George M I" },
   { "convert": [(2086, "Lidster James B"), (2087, "Lidster James B."), (2088, "Lidster Jim B"), ], "to": "Lidster James B" },
   { "convert": [(2090, "Lilaoowala Rashid K"), (2091, "Lilaoowala Rusi K"), ], "to": "Lilaoowala Rashid K" },
   { "convert": [(2096, "Lin Hsiang Phen"), (2110, "Liu Hsiang Phen"), ], "to": "Lin Hsiang Phen" },
   { "convert": [(2101, "Lind Rolad E"), (2102, "Lind Ronald E."), ], "to": "Lind Rolad E" },
   { "convert": [(2107, "Liu David M H"), (2108, "Liu David M. H."), ], "to": "Liu David M H" },
   { "convert": [(2134, "Lopez Choy Efrain"), (2135, "Lopez Efrain"), ], "to": "Lopez Choy Efrain" },
   { "convert": [(2141, "Lovo Gonzalo ALberto"), (2142, "Lovo Gonzalo Alberto"), ], "to": "Lovo Gonzalo ALberto" },
   { "convert": [(2143, "Lowe David M."), (2144, "Lowe David Ming-L"), ], "to": "Lowe David M." },
   { "convert": [(2145, "Lowe David Ming-Li"), (2144, "Lowe David Ming-L"), ], "to": "Lowe David Ming-Li" },
   { "convert": [(2156, "MIzani Mohamad Vali"), (2373, "Mizani Mohamad Vali"), ], "to": "MIzani Mohamad Vali" },
   { "convert": [(2174, "Madhvani Kantilal"), (2175, "Madhvani Kantilal J"), ], "to": "Madhvani Kantilal" },
   { "convert": [(2180, "Maeksalehi Moosa"), (2221, "Maleksalehi Moosa"), ], "to": "Maleksalehi Moosa" },
   { "convert": [(2184, "Mafong Alfonso E."), (2185, "Mafong Alonso E"), ], "to": "Mafong Alfonso E." },
   { "convert": [(2201, "Majia Arturo"), (2317, "Mejia Arturo"), ], "to": "Mejia Arturo" },
   { "convert": [(2204, "Majid Sheikh Ashar"), (2205, "Majid Sheikh Ashar "), ], "to": "Majid Sheikh Ashar" },
   { "convert": [(2213, "Maldonado Ricardo"), (2214, "Maldonado Richardo"), ], "to": "Maldonado Ricardo" },
   { "convert": [(2225, "Malik Gulshan K"), (2226, "Malik Gulshan K."), ], "to": "Malik Gulshan K" },
   { "convert": [(2233, "Mamian Rafy H"), (2234, "Mamian Rafy H."), ], "to": "Mamian Rafy H" },
   { "convert": [(2242, "Mansour Sadeghi Malak Jamshid"), (2243, "Mansour-Sadeghi Malak Jamshed"), ], "to": "Mansour Sadeghi Malak Jamshid" },
   { "convert": [(2253, "Margas Marco Antonio"), (3771, "Vargas Marco Antonio"), ], "to": "Margas Marco Antonio" },
   { "convert": [(2262, "Martinez Paul R"), (2263, "Martinez Paul Robert"), ], "to": "Martinez Paul R" },
   { "convert": [(2270, "Masraff Anthony"), (2284, "Massraff Anthony"), ], "to": "Masraff Anthony" },
   { "convert": [(2271, "Masraff Anthony "), (2270, "Masraff Anthony"), ], "to": "Masraff Anthony" },
   { "convert": [(2273, "Masri Khodor"), (2274, "Masri Khodr M"), (2276, "Masri Krodr M"), ], "to": "Masri Khodor" },
   { "convert": [(2277, "Masri Krodr M."), (2276, "Masri Krodr M"), (2274, "Masri Khodr M"), ], "to": "Masri Krodr M." },
   { "convert": [(2294, "Matni Walid E"), (2295, "Matni Walid E."), ], "to": "Matni Walid E" },
   { "convert": [(2312, "Mehta Satish Chander"), (3866, "Wehta Satish Chandler"), ], "to": "Mehta Satish Chander" },
   { "convert": [(2326, "Mendieta Jose"), (2417, "Mondieta Jose"), ], "to": "Mendieta Jose" },
   { "convert": [(2328, "Mends Haratio"), (2329, "Mends Horation"), ], "to": "Mends Haratio" },
   { "convert": [(2345, "Milosevic Tomislav"), (2618, "Nilosevic Tomislav"), ], "to": "Milosevic Tomislav" },
   { "convert": [(2356, "Mipjahangeri Darious"), (2360, "Mirjahangeri Darious"), ], "to": "Mipjahangeri Darious" },
   { "convert": [(2368, "Mitchell Sam Ballah"), (2369, "Mitchell Samuel Ballah"), ], "to": "Mitchell Samuel Ballah" },
   { "convert": [(2375, "Mizani Mohammad V. "), (2373, "Mizani Mohamad Vali"), ], "to": "Mizani Mohammad V. " },
   { "convert": [(2378, "Mocharam M T"), (2379, "Mocharam M.T"), ], "to": "Mocharam M T" },
   { "convert": [(2380, "Modaresi Bozorg Mehr"), (2436, "Mooaresi Bozurg Mlhr"), ], "to": "Modaresi Bozorg Mehr" },
   { "convert": [(2385, "Moe Louis Chengbin "), (2386, "Moe Louis Chengin"), ], "to": "Moe Louis Chengbin " },
   { "convert": [(2409, "Molina Joaquin A"), (2411, "Molina Joaquin A."), ], "to": "Molina Joaquin A" },
   { "convert": [(2425, "Montalvo Jorge"), (2423, "Montalvo George"), ], "to": "Montalvo George" },
   { "convert": [(2427, "Montalvo Leon "), (2424, "Montalvo George "), ], "to": "Montalvo Leon " },
   { "convert": [(2431, "Montero George Humbert"), (2430, "Montero George H."), ], "to": "Montero George Humbert" },
   { "convert": [(2432, "Montero Jorge H "), (2433, "Montero Jorge H."), ], "to": "Montero Jorge H " },
   { "convert": [(2442, "Moreno Paul Rene"), (2443, "Moreno Raul Rene"), ], "to": "Moreno Paul Rene" },
   { "convert": [(2465, "Movassaghi Kamran"), (2466, "Movassaghi Kamran "), ], "to": "Movassaghi Kamran" },
   { "convert": [(2468, "Mozafarian Fard M"), (2470, "Mozanfarian Fard M."), (2469, "Mozafarian Faru M"), ], "to": "Mozafarian Fard M" },
   { "convert": [(2472, "Mrabu Enoch J"), (2473, "Mrabu Enoch J."), ], "to": "Mrabu Enoch J" },
   { "convert": [(2478, "Mugambi Johnson K"), (2479, "Mugambi Johnson K."), ], "to": "Mugambi Johnson K" },
   { "convert": [(2481, "Muhammed Saidu M"), (2482, "Muhammed Saidu M."), ], "to": "Muhammed Saidu M" },
   { "convert": [(2490, "Mungi David N"), (2491, "Munyi David N"), ], "to": "Mungi David N" },
   { "convert": [(2501, "Mustafa Yoseif M"), (2502, "Mustafa Yousif M"), ], "to": "Mustafa Yoseif M" },
   { "convert": [(2511, "Nachiengtung V"), (2512, "Nachiengtung V."), ], "to": "Nachiengtung V" },
   { "convert": [(2522, "Najmabadi Manouchehr"), (2523, "Najmabadi Manouchehr Fallah"), ], "to": "Najmabadi Manouchehr Fallah" },
   { "convert": [(2528, "Namazi Ali"), (2553, "Nazami Ali"), ], "to": "Namazi Ali" },
   { "convert": [(2530, "Nanda Ranbir B"), (2531, "Nanda Ranbir B."), ], "to": "Nanda Ranbir B" },
   { "convert": [(2534, "Naraghi Holiayoun N"), (2535, "Naraghi Homayoun"), ], "to": "Naraghi Holiayoun N" },
   { "convert": [(2543, "Nasseri Sina Hossein"), (2545, "Nasserisina Hossein"), ], "to": "Nasseri Sina Hossein" },
   { "convert": [(2555, "Nazari Daroush"), (2556, "Nazari Darush F"), ], "to": "Nazari Daroush" },
   { "convert": [(2564, "Nef German"), (2565, "Nef German H."), ], "to": "Nef German" },
   { "convert": [(2566, "Neilsen Walter Federico"), (2613, "Nielsen Walter Federico"), ], "to": "Neilsen Walter Federico" },
   { "convert": [(2571, "Nemoto John I"), (2572, "Nemoto John Isao"), ], "to": "Nemoto John I" },
   { "convert": [(2597, "Ngongi Amos GN"), (2598, "Ngongi Amos Gn"), ], "to": "Ngongi Amos GN" },
   { "convert": [(2612, "Nielsen Walter F"), (2613, "Nielsen Walter Federico"), ], "to": "Nielsen Walter F" },
   { "convert": [(2621, "Ninh La Xuan"), (3805, "Vinh La Xuan"), ], "to": "Ninh La Xuan" },
   { "convert": [(2630, "Njiiri E. Karanja"), (2631, "Njiri E Karanja"), ], "to": "Njiiri E. Karanja" },
   { "convert": [(2635, "Noaib Ahmed"), (2636, "Noaim Ahmed"), ], "to": "Noaim Ahmed" },
   { "convert": [(2640, "Nooraei Mohammad Taghy"), (2641, "Nooraie Mohammad Taghy"), ], "to": "Nooraei Mohammad Taghy" },
   { "convert": [(2644, "Noravian K Sarkiss"), (2651, "Novarian K Sarkiss"), ], "to": "Noravian K Sarkiss" },
   { "convert": [(2647, "Nosseyri Fahrad A."), (2648, "Nosseyri Farhad A"), ], "to": "Nosseyri Fahrad A." },
   { "convert": [(2660, "Nuseibeh Nasib F."), (2661, "Nuseibeh Nasib Fahim"), ], "to": "Nuseibeh Nasib F." },
   { "convert": [(2665, "Nwosu Christopher C"), (2666, "Nwosu Chrostopher C."), ], "to": "Nwosu Christopher C" },
   { "convert": [(2675, "Odonaughy Kipby"), (2742, "Ouonaughy Kirby"), ], "to": "Odonaughy Kipby" },
   { "convert": [(2681, "Ogunfowora Adeniyi O"), (2682, "Ogunfowora Adeniyi O."), ], "to": "Ogunfowora Adeniyi O" },
   { "convert": [(2685, "Ogunsanya Ayodele F"), (2686, "Ogunsanya Ayodele Festus"), ], "to": "Ogunsanya Ayodele F" },
   { "convert": [(2705, "Oktaykan Mehmet Kazim"), (2706, "Oktaykan Mehmet Kazim "), ], "to": "Oktaykan Mehmet Kazim" },
   { "convert": [(2710, "Olufade Adelani O"), (2711, "Olufade Adelani O."), ], "to": "Olufade Adelani O" },
   { "convert": [(2715, "Omid Ahmad"), (2716, "Omid Ahmed"), ], "to": "Omid Ahmad" },
   { "convert": [(2718, "Omid Mohamad H"), (2719, "Omid Mohamad Hossein"), ], "to": "Omid Mohamad Hossein" },
   { "convert": [(2725, "Orfali Faik Makki"), (2726, "Orfali Tariq Makki"), ], "to": "Orfali Faik Makki" },
   { "convert": [(2731, "Osawa Sukeo"), (3217, "Sawa Sukeo"), ], "to": "Osawa Sukeo" },
   { "convert": [(2740, "Ouam Brooke M"), (2936, "Quam Brooke"), ], "to": "Ouam Brooke M" },
   { "convert": [(2744, "Oustouani Mohamed Z"), (2745, "Oustouani Mohamed Z."), ], "to": "Oustouani Mohamed Z" },
   { "convert": [(2746, "Owusu Emmanuel B"), (3737, "Uwusu Emmanuel B"), ], "to": "Owusu Emmanuel B" },
   { "convert": [(2749, "Ozgercin Vedat Ahmet"), (2750, "Ozgercin Vedat Ahmet "), ], "to": "Ozgercin Vedat Ahmet" },
   { "convert": [(2753, "Padilla Armando Callego"), (2755, "Padilla Armando Gallego"), (2754, "Padilla Armando G"), ], "to": "Padilla Armando Callego" },
   { "convert": [(2769, "Pallares Antonio"), (2770, "Pallares Antonio Ignacio"), ], "to": "Pallares Antonio" },
   { "convert": [(2771, "Pallares Tony Ignacio"), (2770, "Pallares Antonio Ignacio"), ], "to": "Pallares Tony Ignacio" },
   { "convert": [(2777, "Papailias Dietrios"), (2779, "Papailias dimitrios"), ], "to": "Papailias Dietrios" },
   { "convert": [(2789, "Parsa Ali A"), (2790, "Parsa Ali A. "), ], "to": "Parsa Ali A. " },
   { "convert": [(2792, "Partovi Thahereh"), (2806, "Patrovi Thahereh"), ], "to": "Partovi Thahereh" },
   { "convert": [(2797, "Pastegar Roosevelt"), (2989, "Rastegar Roosevelt"), ], "to": "Pastegar Roosevelt" },
   { "convert": [(2809, "Peclaris Dimitri"), (2810, "Peclaris Dimitri E."), ], "to": "Peclaris Dimitri" },
   { "convert": [(2818, "Pekary Arpad A."), (2837, "Perkay Arpad A."), ], "to": "Pekary Arpad A." },
   { "convert": [(2830, "Perez Alfonso E"), (2831, "Perez Alfonso E."), ], "to": "Perez Alfonso E" },
   { "convert": [(2845, "Petrowski Ole Harry"), (2846, "Petrowski Oles H."), ], "to": "Petrowski Ole Harry" },
   { "convert": [(2850, "Phan Tuan T"), (2851, "Phan Tuan Tat"), ], "to": "Phan Tuan T" },
   { "convert": [(2852, "Philipovitch Yevegeni"), (2853, "Philipovitch Yevgeni"), ], "to": "Philipovitch Yevegeni" },
   { "convert": [(2863, "Pi Clarence U"), (2864, "Pi Clarence Y"), ], "to": "Pi Clarence U" },
   { "convert": [(2870, "Piloyan Kevork K"), (2871, "Piloyan Kevork K."), ], "to": "Piloyan Kevork K" },
   { "convert": [(2886, "Po Carolina"), (3896, "Wong Carolina"), ], "to": "Po Carolina" },
   { "convert": [(2900, "Prajota"), (2901, "Prajoto"), ], "to": "Prajota" },
   { "convert": [(2923, "Punjani Nazmudin C"), (2924, "Punjani Nazmundin C"), ], "to": "Punjani Nazmudin C" },
   { "convert": [(2932, "Qayam Mohammad Abdu"), (2933, "Qayum Mohammad Abdul"), ], "to": "Qayam Mohammad Abdu" },
   { "convert": [(2945, "Raad Farid H"), (2946, "Raad Farid H."), ], "to": "Raad Farid H" },
   { "convert": [(2947, "Rabikian Zavan Quarabei"), (375, "Babikian Zaven Garabid"), ], "to": "Rabikian Zavan Quarabei" },
   { "convert": [(2955, "Rahin Mohammed D"), (2956, "Rahin Mohammed D."), ], "to": "Rahin Mohammed D" },
   { "convert": [(2964, "Rajabali Habib M"), (2965, "Rajabali Habib M."), ], "to": "Rajabali Habib M" },
   { "convert": [(2976, "Ramos Oscar J"), (2977, "Ramos Oscar J."), ], "to": "Ramos Oscar J" },
   { "convert": [(2998, "Rebaldo Quirico"), (2999, "Rebaldo Quirico R"), (3000, "Rebaldo Quirico Roque"), ], "to": "Rebaldo Quirico" },
   { "convert": [(3003, "Reddock Bertram A"), (3004, "Reddock Bertram A."), ], "to": "Reddock Bertram A" },
   { "convert": [(3010, "Rekanto"), (3057, "Rokanto"), ], "to": "Rekanto" },
   { "convert": [(3012, "Renardo Bonifacio R"), (3013, "Renardo Bonifacio Resos"), ], "to": "Renardo Bonifacio R" },
   { "convert": [(3019, "Rezvani Hooshaug"), (3020, "Rezyani Hooshang"), ], "to": "Rezvani Hooshaug" },
   { "convert": [(3021, "Riat Dharam Signh"), (3022, "Riat Dharam Singh"), ], "to": "Riat Dharam Signh" },
   { "convert": [(3023, "Richardson Sonny E"), (3025, "Richardson Sonny E."), ], "to": "Richardson Sonny E" },
   { "convert": [(3039, "Rivera Carlos R"), (3788, "Veraza Carlos R"), ], "to": "Rivera Carlos R" },
   { "convert": [(3041, "Rizvi Majid H"), (3042, "Rizvi Majid H."), ], "to": "Rizvi Majid H" },
   { "convert": [(3072, "Rosenbloom Zvi J"), (3073, "Rosenbloom Zvi J."), ], "to": "Rosenbloom Zvi J" },
   { "convert": [(3075, "Rothschild Gerhard"), (3076, "Rothschild Gerhard "), (3077, "Rothshild Gerhard"), ], "to": "Rothschild Gerhard" },
   { "convert": [(3079, "Rouhani Ghazaleh"), (3080, "Rouhani Ghazaleh "), ], "to": "Rouhani Ghazaleh" },
   { "convert": [(3081, "Rouhani Shahariar"), (3082, "Rouhani Shahariar "), ], "to": "Rouhani Shahariar" },
   { "convert": [(3092, "Russeini Munther D"), (1591, "Husseini Munther D."), ], "to": "Russeini Munther D" },
   { "convert": [(3102, "Sabounchi Adib M"), (3103, "Sabounchi Adib Mustafa"), ], "to": "Sabounchi Adib M" },
   { "convert": [(3104, "Saboundi Siroos E"), (3107, "Sabouni Siroos E"), ], "to": "Saboundi Siroos E" },
   { "convert": [(3105, "Sabouni Cyrus E"), (3106, "Sabouni Cyrus E."), ], "to": "Sabouni Cyrus E" },
   { "convert": [(3113, "Sadeghi Mohammad Reza"), (3114, "Sadeghi Mohammed R"), ], "to": "Sadeghi Mohammad Reza" },
   { "convert": [(3122, "Safar Mobashar A"), (4015, "Zafar Mobashar A"), ], "to": "Safar Mobashar A" },
   { "convert": [(3123, "Safari Hossein"), (2159, "Maadi Hossein"), ], "to": "Safari Hossein" },
   { "convert": [(3139, "Sakalian Yeghia A"), (3142, "Sakkalian Yeghia A"), ], "to": "Sakalian Yeghia A" },
   { "convert": [(3140, "Sakham Kousoum South"), (3141, "Sakhan Kousoum South"), ], "to": "Sakham Kousoum South" },
   { "convert": [(3145, "Salaverria Raul A"), (3146, "Salaverria Raul Antonio"), ], "to": "Salaverria Raul Antonio" },
   { "convert": [(3148, "Salehi Ahmad"), (3551, "Taleghani Ahmad"), ], "to": "Salehi Ahmad" },
   { "convert": [(3149, "Salehkhou Abbas"), (3150, "Salehkou Abbas"), ], "to": "Salehkhou Abbas" },
   { "convert": [(3160, "Sallum Ghanim Nassif"), (3161, "Sallum Shanim Nassif"), ], "to": "Sallum Ghanim Nassif" },
   { "convert": [(3174, "Sanchez L Jose H"), (3175, "Sanchez L. Jose H."), ], "to": "Sanchez L Jose H" },
   { "convert": [(3183, "Sandhu Shamsher"), (3184, "Sandhu Shamsher S"), ], "to": "Sandhu Shamsher" },
   { "convert": [(3205, "Sarragossa Lucien A "), (3206, "Sarragossa Lucien A."), ], "to": "Sarragossa Lucien A " },
   { "convert": [(3208, "Sarria Jaime*"), (3209, "Sarria James"), ], "to": "Sarria Jaime*" },
   { "convert": [(3211, "Sasak Gun"), (3224, "Sazak Gun"), ], "to": "Sazak Gun" },
   { "convert": [(3223, "Sazak Guh"), (3224, "Sazak Gun"), ], "to": "Sazak Gun" },
   { "convert": [(3225, "Scarpetta Maria"), (3226, "Scarpetta Maria Lia"), ], "to": "Scarpetta Maria" },
   { "convert": [(3230, "Scherf Michael"), (3231, "Scherf Michael "), ], "to": "Scherf Michael" },
   { "convert": [(3232, "Schiutz Hedda"), (3238, "Schmutz Hedda"), ], "to": "Schiutz Hedda" },
   { "convert": [(3247, "Seed Mohd Rahamtalla"), (3248, "Seed Moho Rahamtalla"), ], "to": "Seed Mohd Rahamtalla" },
   { "convert": [(3253, "Sekarchian Rasoul"), (3325, "Shekahchian Rasoul"), ], "to": "Sekarchian Rasoul" },
   { "convert": [(3260, "Sepahrom Mohammad"), (3261, "Sepahroom Mohammad"), ], "to": "Sepahrom Mohammad" },
   { "convert": [(3274, "Shafia Fereidoun Moghtader"), (3275, "Shafia Fereidoun Moghtader (Fred)"), ], "to": "Shafia Fereidoun Moghtader" },
   { "convert": [(3279, "Shah Muzaffar Ali"), (3280, "Shah Muzzafar Ali"), ], "to": "Shah Muzaffar Ali" },
   { "convert": [(3287, "Shahid Khawaja A R"), (3288, "Shahid Khawaja A. R."), ], "to": "Shahid Khawaja A R" },
   { "convert": [(3289, "Shahinian Dick H"), (3290, "Shahinian Dick H."), ], "to": "Shahinian Dick H" },
   { "convert": [(3293, "Shami Victor S"), (3294, "Shami Victor S."), ], "to": "Shami Victor S" },
   { "convert": [(3299, "Shaolian Noorolla"), (3344, "Shoalian Noorolla"), ], "to": "Shaolian Noorolla" },
   { "convert": [(3303, "Sharei Manoutchehr"), (3352, "Siani Manouchehr"), (1744, "Karami Manouchehr"), ], "to": "Karami Manouchehr" },
   { "convert": [(3312, "Sharma Rajinder Paul"), (3313, "Sharma Rajinder Paul "), ], "to": "Sharma Rajinder Paul" },
   { "convert": [(3318, "Sheikhaleslami E"), (3323, "Sheikmaleslami E"), (3321, "Sheikholeslami M"), ], "to": "Sheikhaleslami E" },
   { "convert": [(3322, "Sheikholeslami S."), (3321, "Sheikholeslami M"), ], "to": "Sheikholeslami S." },
   { "convert": [(3324, "Sheikoleslami Kazem"), (3321, "Sheikholeslami M"), ], "to": "Sheikoleslami Kazem" },
   { "convert": [(3330, "Shenassa Sassoon"), (3331, "Shenassa Sassoon Bakhaj"), ], "to": "Shenassa Sassoon" },
   { "convert": [(3339, "Shing Sze Kong"), (3340, "Shing Sze Ling"), ], "to": "Shing Sze Kong" },
   { "convert": [(3349, "Shumshere Rana K"), (3350, "Shumshere Rana K."), ], "to": "Shumshere Rana K" },
   { "convert": [(3360, "Sidhartha F M"), (3361, "Sidhartha F.X"), ], "to": "Sidhartha F M" },
   { "convert": [(3363, "Sidhu Arjan Singh"), (3364, "Sidhu Gurdas Singh"), ], "to": "Sidhu Arjan Singh" },
   { "convert": [(3365, "Sidhu Hohinder Singh"), (3367, "Sidhu Joginder Singh"), (3411, "Sodhi Harinder Singh"), ], "to": "Sidhu Hohinder Singh" },
   { "convert": [(3366, "Sidhu Joginder S."), (3367, "Sidhu Joginder Singh"), ], "to": "Sidhu Joginder S." },
   { "convert": [(3370, "Silva Antonio D"), (3372, "Silva Antonio G.R.L"), ], "to": "Silva Antonio D" },
   { "convert": [(3374, "Silvia Antonio D. G. R."), (3372, "Silva Antonio G.R.L"), ], "to": "Silvia Antonio D. G. R." },
   { "convert": [(3376, "Simbarohije Daniel"), (3377, "Simbaruhije Daniel"), ], "to": "Simbaruhije Daniel" },
   { "convert": [(3383, "Sinclair Benito A."), (3384, "Sinclair Benito Augustus"), ], "to": "Sinclair Benito A." },
   { "convert": [(3394, "Sio Gilbert W"), (3404, "Siu Gilbert W"), ], "to": "Sio Gilbert W" },
   { "convert": [(3423, "Soffia Eduardo A"), (3424, "Soffia Eduardo A."), ], "to": "Soffia Eduardo A" },
   { "convert": [(3427, "Solari Nestor"), (3428, "Solari Nestor A"), ], "to": "Solari Nestor" },
   { "convert": [(3432, "Soleimani Manouchehr"), (3352, "Siani Manouchehr"), ], "to": "Soleimani Manouchehr" },
   { "convert": [(3434, "Soliz Caston Abel"), (3435, "Soliz Gaston Abel"), ], "to": "Soliz Caston Abel" },
   { "convert": [(3443, "Soni Gurcharan S"), (3444, "Soni Gurcharan S."), ], "to": "Soni Gurcharan S" },
   { "convert": [(3445, "Soofi Abdollah S"), (3446, "Soofi Abdollah S."), ], "to": "Soofi Abdollah S" },
   { "convert": [(3447, "Soofi Ehsanolah S"), (3448, "Soofi Ehsanolah S."), ], "to": "Soofi Ehsanolah S" },
   { "convert": [(3455, "Soroudi Parvitz"), (3456, "Soroudi Parviz"), ], "to": "Soroudi Parvitz" },
   { "convert": [(3458, "Soroushian Manoochehr F."), (3457, "Soroushian Manoochehr"), ], "to": "Soroushian Manoochehr F." },
   { "convert": [(3474, "Spyropoylos Tom S"), (3475, "Spyropoylos Tom S."), ], "to": "Spyropoylos Tom S" },
   { "convert": [(3476, "Sridijarno"), (3477, "Sridijarso"), ], "to": "Sridijarno" },
   { "convert": [(3479, "Stamatelos Doannis N"), (3480, "Stamatelos Joannis N"), ], "to": "Stamatelos Joannis N" },
   { "convert": [(3493, "Suarez Emiterio"), (3494, "Suarez Emiterio C"), ], "to": "Suarez Emiterio" },
   { "convert": [(3506, "Sultan Najib A G"), (3507, "Sultan Najib A G "), (3508, "Sultan Najib A. G. "), ], "to": "Sultan Najib A G" },
   { "convert": [(3514, "Sung Paul Yun-Fai"), (3516, "Sung Paul Yun-Thai"), ], "to": "Sung Paul Yun-Fai" },
   { "convert": [(3536, "Taheri Ali A"), (3537, "Taheri Ali Asghar"), ], "to": "Taheri Ali A" },
   { "convert": [(3544, "Taiwo Olufjnke"), (3545, "Taiwo Olufunke"), ], "to": "Taiwo Olufjnke" },
   { "convert": [(3546, "Taja Mohindar Singh"), (3594, "Teja Mohindar S"), (993, "Dhaliwal Mohindar Singh"), ], "to": "Taja Mohindar Singh" },
   { "convert": [(3555, "Tan Joseph H"), (3556, "Tan Josseph H."), ], "to": "Tan Joseph H" },
   { "convert": [(3561, "Taneja Om Prakash "), (3600, "Tenja Om Prakash"), ], "to": "Taneja Om Prakash " },
   { "convert": [(3569, "Tapia Alberto"), (3570, "Tapia Alberto "), ], "to": "Tapia Alberto" },
   { "convert": [(3582, "Tawakol Ebrahim M"), (3583, "Tawakol Ebrahim M."), ], "to": "Tawakol Ebrahim M" },
   { "convert": [(3597, "Telmo Frisco"), (3598, "Telmo Frisco T."), ], "to": "Telmo Frisco" },
   { "convert": [(3609, "Thapar Raj Kumar"), (3610, "Thapar Raj Kumar "), ], "to": "Thapar Raj Kumar" },
   { "convert": [(3617, "Thiessen Clarence P."), (3618, "Thiessen Clarence Peter "), ], "to": "Thiessen Clarence P." },
   { "convert": [(3624, "Thompson Emil S"), (3625, "Thompson Emil S."), ], "to": "Thompson Emil S" },
   { "convert": [(3633, "Tobias Jorge"), (3634, "Tobias Jorge A"), ], "to": "Tobias Jorge A" },
   { "convert": [(3651, "Torrico Jorge"), (3652, "Torrico Jorge A."), ], "to": "Torrico Jorge" },
   { "convert": [(3654, "Touserkani Hadi"), (3655, "Touserkuri Hadi"), ], "to": "Touserkani Hadi" },
   { "convert": [(3683, "Tum Dean J"), (3684, "Tum Dean J."), ], "to": "Tum Dean J" },
   { "convert": [(3685, "Tuma Yousif S"), (3686, "Tuma Yousif S."), ], "to": "Tuma Yousif S" },
   { "convert": [(3704, "Ubhi Avtar"), (3709, "Ubli Avtar S"), ], "to": "Ubhi Avtar" },
   { "convert": [(3706, "Ubieto Herman"), (3708, "Ubieto Hernan"), (3707, "Ubieto Hermin"), ], "to": "Ubieto Herman" },
   { "convert": [(3713, "Udo Aka Sunday"), (3733, "Uro Aka Sunday"), ], "to": "Udo Aka Sunday" },
   { "convert": [(3714, "Ufer Ernest Oscar"), (3715, "Ufer Ernst Oscar"), ], "to": "Ufer Ernest Oscar" },
   { "convert": [(3725, "Urfali Dhiaddin Sami"), (3726, "Urfali Diaddin Sami"), ], "to": "Urfali Diaddin Sami" },
   { "convert": [(3743, "Valdes Isadro Edmund"), (3749, "Valdez Isidro Edmundo"), (3746, "Valdes Isidro E"), ], "to": "Valdes Isidro E" },
   { "convert": [(3744, "Valdes Isidora E "), (3746, "Valdes Isidro E"), ], "to": "Valdes Isidro E" },
   { "convert": [(3751, "Valdivieso Cipriano"), (3757, "Valivieso Cipriano"), ], "to": "Valdivieso Cipriano" },
   { "convert": [(3761, "Van Heden Paul"), (3764, "Vanheden Paul"), ], "to": "Vanheden Paul" },
   { "convert": [(3767, "Vanughese Jacob"), (3774, "Varughese Jacob"), ], "to": "Vanughese Jacob" },
   { "convert": [(3768, "Varela Guillermo J"), (3769, "Varela Guillermo J."), ], "to": "Varela Guillermo J" },
   { "convert": [(3792, "Verushalmi Daryoush"), (3966, "Yerushalmi Daryoush"), ], "to": "Yerushalmi Daryoush" },
   { "convert": [(3793, "Vibhathawach Chumnan"), (3797, "Vihhathawach Chumnan"), ], "to": "Vibhathawach Chumnan" },
   { "convert": [(3799, "Villaneuva Pablo Villaneuva"), (3800, "Villanueva Pablo Villaneuva"), ], "to": "Villaneuva Pablo Villaneuva" },
   { "convert": [(3806, "Vinh Laxuan"), (3805, "Vinh La Xuan"), ], "to": "Vinh Laxuan" },
   { "convert": [(3814, "Von Engelbrechten Jan"), (3815, "Von Engelbrecten Jan"), ], "to": "Von Engelbrechten Jan" },
   { "convert": [(3826, "Wahl Robert P"), (3827, "Wahl Robert Paul"), ], "to": "Wahl Robert P" },
   { "convert": [(3834, "Wang Hsui Sheng"), (3844, "Want Hsiu Sheng"), ], "to": "Wang Hsui Sheng" },
   { "convert": [(3845, "Warbedian Leon M"), (3846, "Warbedian Leon M."), ], "to": "Warbedian Leon M" },
   { "convert": [(3851, "Warshawski Gearldine Faye"), (3853, "Warshawski Geraldine Faye"), ], "to": "Warshawski Gearldine Faye" },
   { "convert": [(3856, "Wasbrough William"), (3857, "Wasbrough William Charles"), ], "to": "Wasbrough William" },
   { "convert": [(3881, "Widgen Jinder K"), (3882, "Widgen Rajinder K."), ], "to": "Widgen Jinder K" },
   { "convert": [(3883, "Wilkowsky Karim F"), (3884, "Wilowsky Karin F."), ], "to": "Wilkowsky Karim F" },
   { "convert": [(3891, "Won Miu Ling"), (3906, "Wong Miu Ling "), ], "to": "Won Miu Ling" },
   { "convert": [(3892, "Wong Andrew Man K"), (3893, "Wong Andrew Man K."), ], "to": "Wong Andrew Man K" },
   { "convert": [(3920, "Wu Augustine Bick"), (3921, "Wu Augustine Bick L "), ], "to": "Wu Augustine Bick" },
   { "convert": [(3922, "Wu Ronny Yim Cheung"), (3924, "Wu Yim Cheung"), ], "to": "Wu Yim Cheung" },
   { "convert": [(3925, "Wumnawa Jacob K"), (3926, "Wumnaya Jacob K"), (3927, "Wumnaya Jacob K."), ], "to": "Wumnawa Jacob K" },
   { "convert": [(3929, "Yahagi Seizo"), (3981, "Yohagi Seizo"), ], "to": "Yahagi Seizo" },
   { "convert": [(3930, "Yahalom Yair"), (3949, "Yashalom Yair"), ], "to": "Yahalom Yair" },
   { "convert": [(3932, "Yahya Abdulilah"), (3933, "Yahya Abdulilah A."), ], "to": "Yahya Abdulilah" },
   { "convert": [(3935, "Yan Yen Chiu"), (3936, "Yan Yuen Chiu "), ], "to": "Yan Yen Chiu" },
   { "convert": [(3938, "Yanai Hideyasa Steve"), (3939, "Yanai Hideyasu Steve"), ], "to": "Yanai Hideyasa Steve" },
   { "convert": [(3948, "Yasemi Mohamad"), (3954, "Yassemi Mohamed"), ], "to": "Yasemi Mohamad" },
   { "convert": [(3951, "Yashri Ehsanollah"), (3960, "Yazhari Ehsanollah"), ], "to": "Yashri Ehsanollah" },
   { "convert": [(3963, "Yazhary Ezatollah"), (3960, "Yazhari Ehsanollah"), ], "to": "Yazhary Ezatollah" },
   { "convert": [(3969, "Yeung Peter"), (3992, "Young Peter H"), ], "to": "Yeung Peter" },
   { "convert": [(3976, "Ying Kester K"), (3977, "Ying Kester K."), ], "to": "Ying Kester K" },
   { "convert": [(3979, "Yo John Hoey Tjoe"), (3980, "Yo John-Hoey Tjoe"), ], "to": "Yo John Hoey Tjoe" },
   { "convert": [(3983, "Yomtobian Manoochehr"), (1300, "Gohodsian Manoochehr"), ], "to": "Yomtobian Manoochehr" },
   { "convert": [(3996, "Yousif Michael"), (3997, "Youssif Michael"), ], "to": "Yousif Michael" },
   { "convert": [(4020, "Zahedi Abolghaseem"), (4021, "Zahedi Abolghassem"), ], "to": "Zahedi Abolghaseem" },
   { "convert": [(4044, "Zee Joseph S C"), (4045, "Zee Jospeh S. C."), ], "to": "Zee Joseph S C" },
   { "convert": [(4050, "Zghaib Camille A "), (4051, "Zghaib Kamil A"), ], "to": "Zghaib Camille A " },
   { "convert": [(4053, "Zilka Latif Moshi"), (4056, "Zitka Latif Moshi"), ], "to": "Zilka Latif Moshi" },
   { "convert": [(4059, "Zok Mohamad F "), (4060, "Zok Mohamed"), ], "to": "Zok Mohamad F " },
   { "convert": [(4062, "Zuazo Hermes R"), (4063, "Zuazo Hermes R."), ], "to": "Zuazo Hermes R." },
]
